### ISSUE TITLE
Development mode?

### ISSUE THREAD

**Issue by foag** [bennettstone/magic-min#1]
Maybe I'm not reading the documentation correctly, but I'd really appreciate some kind of brute option to force recompilation of the files while in development. 

Maybe passed as an argument to the class?

The issue for me is that I'm using magic-min to merge/compress/minify a specific list of both css and js (in separate instances), which works awesome, but since I'm still in pretty heavy development I tend to update both base CSS and JS quite heavily. 
The caching prevents changes from being added, thus making it desirable to override that option and forcing the instance to remake the files.

**Comment by smartcorestudio** [comment]
+1

**Comment by bennettstone** [comment]
Noted and updated to 3.0.4 with additional construct param of "force_rebuild":  https://github.com/bennettstone/magic-min/commit/6796da11328f182e0205b3509a273622346d7b98
