### ISSUE TITLE
JS doesnt work at all

### ISSUE THREAD

**Issue by kallevaravas** [bennettstone/magic-min#3]
First off, Thanks! Was fun getting the backup files from the server. As you say that one is the source file and second one is the OUTPUT file. Worked other way around.

And non of the JS functions really worked. So YOU deleted all my JS. Thanks for that.

Closure from google, doesn't work. jShrink.php didn't work. While you say in your description, that there must be jsmin.php file in the same directory?!?! Confusing.

All in all, not what I'm looking for as it doesn't work. And I have no clue how it is meant to be working.

**Comment by bennettstone** [comment]
Check your paths and try something like this gist: https://gist.github.com/bennettstone/d2a08c641d38c14d697b (you're welcome.)
